name: nano_health
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.2.0+1
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  ms_material_color: ^1.0.0
  flutter_svg: ^2.0.6
  flutter_rating_bar: ^4.0.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/svg/
    - assets/svg/navbar/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Regular.ttf
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/sf_pro_text/SFProText-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
          weight: 300